spring:
  application:
    name: demo_liquibase
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: sa
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.yaml
    enabled: false